FROM golang:1.19-bullseye

RUN apt-get update && \
    apt-get install -y \
    apt-transport-https \
    ca-certificates \
    protobuf-compiler \
    libc6-dev \
    libprotobuf-dev \
    python3 \
    python3-pip

ENV GO111MODULE=on

RUN go install github.com/uber/prototool/cmd/prototool@v1.10.0
RUN go install github.com/golang/protobuf/protoc-gen-go@v1.5.2
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

ENV GO111MODULE=off

RUN go get -d github.com/grpc-ecosystem/grpc-gateway/... && \
    go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway && \
    go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger

RUN pip3 install grpcio grpcio-tools

WORKDIR /go/src/github.com/aunum/sphere
